# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15WB7nlSw80f3u8YZiNr4Dthmw39cXSaR
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = sns.load_dataset('titanic')

df

# 1. survived 생존 여부 0이면 사망, 1이면 생존
# 2. pclass 객실 등급 1이면 1등급, 2이면 2등급, 3이면 3등급
# 3. sex 성별 male이면 남자, female이면 여자
# 4. age 나이
# 5. sibsp 함께 탑승한 형제 및 배우자 수
# 6. parch 함께 탑승한 자녀 및 부모 수
# 7. fare 요금
# 8. embarked 탑승지 이름 앞글자 C는 Cherbourg, Q는 Queenstown, S는 Southampton
# 9. class 객실 등급 First면 1등급, Second면 2등급, Third면 3등급
# 10. who 남자, 여자, 아이man, woman, child
# 11. adult_male 성인 남자인지 여부 True면 성인 남자, False면 그외
# 12. deck 선실 번호 첫 알파벳A, B, C, D, E, F, G
# 13. embark_town 탑승지 이름 Cherbourg, Queenstown, Southampton
# 14. alive생존여부no면 사망, yes면 생존
# 15. alone 혼자 탑승했는지 여부 True면 혼자 탑승, False면 가족과 함께 탑승

#연습) 다음을 연습해 봅니다.                            완성하면 "1"
# 1. 성별별 생존율
# 2. 객실 등급에 따른 생존자
# 3. 객실 등급에 따른 남여 생존율